name: Run Python Script
on:
  push:
    branches:
      - main
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install NLTK data
        run: python -c "import nltk; nltk.download('punkt_tab'); nltk.download('averaged_perceptron_tagger')"
      - name: Install Java for LanguageTool
        run: sudo apt-get update && sudo apt-get install -y openjdk-11-jre
      - name: Run script
        run: python scripts/script.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: debug-logs
          path: debug.log
